### PR TITLE
feat(e2-992): Added Send_push_open_url button.

### PR DESCRIPTION
**Pull request by sayaansaha**
Needed for Push Notification with Open Url functional tests.

### CODE REVIEW

**Review by acconway — APPROVED** [review]

**Review by Enuviel — CHANGES_REQUESTED** [review]
Where is button for in-app test?

**Comment by acconway** [comment]
@Enuviel -- I already added the in-app button https://github.com/Leanplum/Leanplum-Android-SDK-Example/blob/7dce84593ade72a8d54168233739ac2becb1620d/app/src/main/java/com/leanplum/android/example/fragments/TestingInAppFragment.java#L76

**Comment by Enuviel** [comment]
@acconway  cool, thanks

**Review by Enuviel — APPROVED** [review]

**Comment by Enuviel** [comment]
@sayaansaha  could you please merge it. Thanks!

**Pull request merged**
